### ISSUE TITLE
Comment on blog page

### ISSUE THREAD

**Issue by philippneugebauer** [wireddown/ghpages-ghcomments#11]
Would be great if you can comment directly on the blog page without redirecting

Githup api provides this possibility: https://developer.github.com/v3/issues/comments/

**Comment by wireddown** [comment]
I also agree this is desirable, and that the API provides a way to create comments on issues. I will need to research it further.

What capabilities should the reader have?

For example, the reader should have the ability to:

1. write a comment in markdown
1. see a preview of their comment
1. login
1. _your ideas here_

**Comment by wireddown** [comment]
I believe this might not be possible, or more *truthfully*, not possible for the amount of security accountability and JavaScript complexity I want to implement and maintain.

The largest obstacle appears to be **authentication**: how can a post's web page authenticate a reader with GitHub so that the Comments API will accept a new comment?

Besides creating a login form, I can't imagine another way to accomplish this. Gone are the shady days of digging around the browser's cookies looking for user credentials ;-) Implementing a login form is a Hard Thing:

* not only must the form be secure and hardened against attacks, but
* GitHub also allows users to require [two-factor-authentication](https://developer.github.com/v3/auth/) (*a feature I wish every site would offer*), which means the login form would need to be stateful.

I did a quick "post a comment" sketch this evening, and I definitely encountered the [not-authorized **404** response](https://developer.github.com/v3/troubleshooting/#why-am-i-getting-a-404-error-on-a-repository-that-exists) GitHub uses to shield private repositories.

Can you think of another way to allow a reader to submit a comment from a blog post page?

**Comment by philippneugebauer** [comment]
Sounds much more complicated than I expected it to be. If I remember right, the predecessor solution in the blog you published your solution looked a lot like real GitHub, so he maybe just included the github issue page? Could that be a solution? Another thought would be just to slip it to a GitHub employee and he could propose another solution. Your idea merits to get promoted!

**Comment by wireddown** [comment]
> If I remember right, the predecessor solution in the blog you published your solution looked a lot like real GitHub, so he maybe just included the github issue page?

I believe [this](http://ivanzuzak.info/2011/02/18/github-hosted-comments-for-github-hosted-blogs.html) is the blog you're remembering. It looks like Ivan did not include the Issue page, but just adjusted his CSS so that it appeared to be the same. The only request his page makes to GitHub is `https://api.github.com/repos/izuzak/izuzak.github.com/issues/12/comments?per_page=100`

> Could that be a solution?

I see a few obstacles to overcome, and I'm not sure I could solve all of them:

1. By including the Issue page (or even a subset of it), it will become more difficult to apply look and feel to html elements since they will be decorated with GitHub's CSS classes.
1. I'm not sure if GitHub's *Add Comment* implementation complies with CORS. Perhaps their JavaScript uses HTTP headers or content that CORS will not allow.
1. Finally, I'm not sure how GitHub authenticates its users on its own pages. Using the browser console, I see that tokens are being used in the HTTP headers, but I'm not sure a non-GitHub site will have access to where they are stored. Cookies are sandboxed these days...

I will try it though to see what happens.

> Another thought would be just to slip it to a GitHub employee and maybe he could propose another solution. Your idea merits to get promoted!

There aren't a lot of them out here in Texas, but I'm not opposed to campaigning for guidance. :-)

##### The last fallback I can see is:

1. Use the `/markdown` [API](https://developer.github.com/v3/markdown/) to allow a user to write and preview their comment.
1. Open the Issue page in a new tab when the reader clicks or taps the *Leave a Comment* button.
1. Expect or instruct the reader to copy-and-paste their markdown into the GitHub form.

**Comment by naveenshaji** [comment]
Why not use gists instead of issues? There are a lot of apps making use of gists. You can skip the login part and use a mock github account for the website. Each post has an associated gist with it, and every time a user comments on a post, a new line or something is added after a delimiter for separation through said mock account. And then again use gist API to query the gist and use javascript to separate comments based on the delimiter and display them under the post? Is this possible at all?

Or even if that is not possible then I'm sure you can set it such that each comment is posted as an anonymous gist with a title of some format such as MD5(sitename+postname) or so. And then later query those for each post based on title. 

^^ This is based on my limited knowledge which I've gathered from [here](https://developer.github.com/v3/gists/) in the past 5 minutes. Correct me if I'm wrong here.

**Comment by wireddown** [comment]
## Suggestion: Include the GitHub Issue page (or a segment) on the blog post

> *[wireddown](https://github.com/wireddown/ghpages-ghcomments/issues/11#issuecomment-74307636):*
>
> I see a few obstacles to overcome, and I'm not sure I could solve all of them:
> 
> 1. By including the Issue page (or even a subset of it), it will become more difficult to apply look and feel to html elements since they will be decorated with GitHub's CSS classes.

**I will not pursue this** because, in my layman's opinion, this technique would violate the GitHub Terms of Service:

> *GitHub [Terms of Service](https://help.github.com/articles/github-terms-of-service/):*
>
> **[Section G](https://help.github.com/articles/github-terms-of-service/#g-general-conditions), article 4**
> You must not modify, adapt or hack the Service or modify another website so as to falsely imply that it is associated with the Service, GitHub, or any other GitHub service.

Co-opting the Issue page would *modify another website* (eg, the blog site) and give it the appearance and behavior of GitHub. Whether or not doing so would *falsely imply it is associated* with GitHub is then up to legal interpretation. I do not want to risk my account being suspended or revoked, nor do I want to defend my humble project in court.

## Suggestion: Use Gists instead of Issues to store comments

> *[naveenshaji](https://github.com/wireddown/ghpages-ghcomments/issues/11#issuecomment-74376174):*
>
> Why not use gists instead of issues?

This is a creative suggestion. Thanks :-)

For the time being, **I will wait** until GitHub or the API lowers some of the (currently solvable) barriers such that I can make the implementation:

* more secure, and
* with less effort

I have written a long response, and I want to explicitly state my intention: when I revisit this Issue in the future, I need an exact list of pain points for Gists. In that new future, I can then compare this list against the new GitHub capabilities to determine if using this approach is feasible. I'm worried that you'll read this as a personal critique when instead it's a checklist for my future self :-)

### Benefits

Not surprisingly, the primary benefits with this technique address the not only this issue, but another one:

1. *(this issue)* A comment form can be placed on the blog post and a reader can add a comment without going to GitHub.
1. *(new issue)* A reader can leave a comment even if they do not have a GitHub account.

Both of these are possible because GitHub allows [anonymous Gists](https://developer.github.com/v3/gists/#authentication). Here's an example:

Gist: [Anonymously Created Gist](https://gist.github.com/anonymous/695eeeac88091fc2deb0)

**curl** command:

`curl -i --request POST -d "{\"description\":\"This gist was created via 'curl'\",\"public\":true,\"files\":{\"Anonymously Created Gist\":{\"content\":\"Created anonymously\"}}}" https://api.github.com/gists`

### Costs

There are several drawbacks to using Gists as a commenting system. Some of the drawbacks are introduced by the nature of Gists, while others are introduced by the constraints in the GitHub v3 API.

#### 0. Gists and the API

First, some background on Gists and the API. Before today, I had never used the `/gists` API, so there may be gaps in my knowledge.

GitHub allows anonymous *creation* of Gists (as shown above), but **does not allow** the anonymous *editing* of Gists. Here's an example of updating a Gist:

Gist: [Anonymous Gist Update](https://gist.github.com/wireddown/9f57755cb0e06e3777c0/revisions)

**curl** command:

`curl -i --request PATCH -d "{\"files\":{\"Anonymous Gist Update\":{\"content\": \"Updated from curl\"}}}" https://api.github.com/gists/9f57755cb0e06e3777c0`

As it is right now, the `curl` command fails with a **404**, even though `curl` can successfully *GET* the Gist at the same URL: `curl https://api.github.com/gists/9f57755cb0e06e3777c0`. This is the same *Not found* response GitHub uses when the client hasn't authenticated with GitHub so that GitHub doesn't expose private repositories. When I add `-H "Authorization: token 123..def"` to the command and use my GitHub OAuth token, `curl` succeeds and I can edit the Gist.

#### 1. API Constraint: every comment must be a new, anonymous Gist

Since Gists cannot be updated anonymously, new comments must be new Gists.

The largest counterpoint to this statement is likely: *"Why not just make the JavaScript use the owner's OAuth token so that the comments Gists can be updated?"* There are two reasons:

1. Even though there is `gist` token [scope](https://developer.github.com/v3/oauth/#scopes), if the JavaScript is able to use it, then the browser has it in the page's source, which means the reader has it. **Now a reader can impersonate you** :-\
1. Even if you were comfortable allowing any reader to use your token, GitHub is not. Doing so violates their Terms of Service:

> *GitHub [Terms of Service](https://help.github.com/articles/github-terms-of-service/)*
>
> **[Section A](https://help.github.com/articles/github-terms-of-service/#a-account-terms), article 4**
> Your login may only be used by one person - a single login shared by multiple people is not permitted.
>
> **[Section A](https://help.github.com/articles/github-terms-of-service/#a-account-terms), article 7**
> One person or legal entity may not maintain more than one free account.

#### 2. Gist Consequence: any GitHub user can impersonate any commenter

Unlike repositories, which require `push` permissions before their contents can be changed, anyone with a GitHub account can edit a Gist. **Any GitHub user can add, remove, or delete the contents of any or all comments**. This two large impacts:

1. You as the blog owner cannot guarantee the authenticity of your commenters' identities.
1. Commenters cannot control the content of their comments.

#### 3. API Constraint: finding Gists is slow, expensive, and not guaranteed

I was surprised to see that the `/search` [API](https://developer.github.com/v3/search/) did not provide a method for searching Gists. Instead, GitHub offers [two ways](https://developer.github.com/v3/gists/#list-gists) to get Gists:

1. `GET /users/:username/gists`
1. `GET /gists/public`

The first only applies to user-created Gists, but comments must be anonymous, so that approach does not apply. The second returns a **large** quantity of results, as the header contains the GitHub [pagination](https://developer.github.com/guides/traversing-with-pagination/#basics-of-pagination) `Link` header:

> `Link:	<https://api.github.com/gists/public?page=2>; rel="next", <https://api.github.com/gists/public?page=100>; rel="last"`

There are 100 30-Gist pages. The only way to reduce the amount of data is by using the [`since` parameter](https://developer.github.com/v3/gists/#parameters), which only returns Gists that have been updated at or after the time specified. Conceivably, this would significantly reduce the possible results, but when I tried `https://api.github.com/gists/public?since=2015-02-14` to get today's modified Gists, there were still 100 pages in the `Link` header.

I confirmed that **GitHub is throttling the results**: by going to the [last page](https://api.github.com/gists/public?since=2015-02-14&page=100) and looking at the last Gist, I saw it had `"updated_at": "2015-02-14T13:59:22Z"`. So in less than 12 hours, there were more than 3000 Gists created. I tried to go the [101st page](https://api.github.com/gists/public?since=2015-02-14&page=101) and received this response:

```
{
  "message": "In order to keep the API fast for everyone, pagination is limited for this resource. Check the rel=last link relation in the Link response header to see how far back you can traverse.",
  "documentation_url": "https://developer.github.com/v3/#pagination"
}
```

Iterating over so many Gists will be slow, and since GitHub is throttling their results, **it's possible that the comments Gist will never be found**.

In addition, making so many anonymous API calls from a single blog page will quickly **hit the 60 requests per hour [rate limit](https://developer.github.com/v3/#rate-limiting)**. When the limit is reached, the reader will see that comments are no longer on the pages and perceive that something broke when in fact they should come back in an hour.

#### 4. Gist Consequence: no one is notified when a comment is added

GitHub does not notify anyone when Gists are created, and I suspect they will never notify anyone when an *anonymous* Gist has been created. You and your readers must instead revisit or refresh the page to see if a comment has been added, which hinders natural conversation and risks reaching the rate limit.

#### 5. Gist Consequence: comments are detached from their blog repository

Anonymous Gists cannot be associated with a user's profile or a repository, so it's hard for readers to know how or even if a Gist is attached to a blog post.

Gists created by users are only associated with the user on https://gist.github.com/wireddown and not https://www.github.com/wireddown.

**Comment by naveenshaji** [comment]
>@wireddown:
>For the time being, I will wait until GitHub or the API lowers some of the (currently solvable) barriers

Well, hope they do that soon. For now my blog will have to remain without comments. I'm not such a big fan of disqus or other cloud hosted solutions and I have to say you are doing a great job trying to contain the comments within GitHub itself, but the current method of using issues does not appeal to me due to users being taken out of my blog, onto GitHub while commenting. 

On another note, why not maintain a single pre-created gist for a whole website, and use different delimiters or specific XML-kinda syntax for separating comments of different posts? Although this method would entail users to log-in to github for getting an OAuth token, It is still a better method than the current one in the sense that it allows for customized built-in comment-forms on the blog. The security problem persists because the gist would be an anon one and anyone with the url and a github account would be able to edit it like you mentioned, but this is also the fact that makes this method feasible.
>@wireddown:
>Unlike repositories, which require push permissions before their contents can be changed, anyone with a GitHub account can edit a Gist. Any GitHub user can add, remove, or delete the contents of any or all comments.

Also, even if somebody wants to mess up the comments manually after figuring out its ID, the site owner could easily move this to another gist which would be a fork of a previous revision before it was messed up.

**Comment by wireddown** [comment]
I thought about this some more, and I think have a contingency that will help while we wait for GitHub to make it easier. I'd like to respond to your thoughtful reply first, though, so skip to the bottom if you want to see it now.

> *[@naveenshaji](https://github.com/wireddown/ghpages-ghcomments/issues/11#issuecomment-74423276)*
>
> For now my blog will have to remain without comments. *\<snip\>* the current method of using issues does not appeal to me due to users being taken out of my blog, onto GitHub while commenting. 

Yes, I agree that the current reader experience is discontinuous and likely confusing. I believe my proposal below will allow you to have an on-blog comment form in trade for a one-time reader effort.

> *[@naveenshaji](https://github.com/wireddown/ghpages-ghcomments/issues/11#issuecomment-74423276)*
>
> why not maintain a single pre-created gist for a whole website, and use different delimiters or specific XML-kinda syntax for separating comments of different posts? *\<snip\>* The security problem persists because the gist would be an anon one and anyone with the url and a github account would be able to edit it like you mentioned

I prefer to not use a design like that because I value security over user experience. Information security and identity authenticity is built-in to GitHub, and I do not want undermine their efforts. I concede that this project is both low-use and low-severity, and if a security hole or flaw was exploitable, the likelihood that an attacker would choose to use it is nearly zero. My only counter argument is: I would rather be a trustworthy source of tools.

## Design Tenets

To that end, I turned on the wiki feature for this repository and added a [Design Tenets](https://github.com/wireddown/ghpages-ghcomments/wiki/Design-Tenets) page so that discussions about trade-offs can have a single source of priority. I hope it will also make arriving at and understanding decisions easier.

I have both observed and participated in several FOSS projects that only had 'tribal knowledge' of how decisions are made scattered in their mailing lists. Such soft and disparate guidelines created a lot of frustration for users and developers. It appeared like the project leaders would create new rules on-the-spot to veto a decision. With these tenets, I hope to disclose how priorities are balanced.

## Proposal

GitHub forbids multiple people from sharing a single login, which prevents the comments feature from using the site owner's OAuth token to update the comments. Similarly, the comments feature cannot access the reader's GitHub cookies that GitHub would use when the reader is interacting with GitHub's pages. However, **what if we asked the reader to create and give us an OAuth token**?

### Description

Here's a (minimum viable) possible interaction:

1. A new reader visits your blog and wants to make a comment.
1. The page has two input fields:
   * the comment form
   * an OAuth token form
1. Once the reader fills in both, they click or tap a *Submit Comment* button.
1. Later, when they return, the page only shows the comments form since the reader's OAuth token is stored in a cookie.

There are several levels of polish that can be applied to help the reader:

* Provide on-page guidance about how to create and use the OAuth token.
* Validate that the token has the appropriate `scope` to make comments on Issues, and disable the *Submit Comment* button until the token is valid.
* Provide feedback when the token isn't valid and reasons why is might be invalid.
* Mimic the GitHub comment form and provide a markdown field for input and a preview mode to see the final presentation.
* *your ideas here*

### Implementation

I'm a strong advocate for always delivering value and delight.

![Minimum Viable Product](https://pbs.twimg.com/media/BzmAjxKIIAAw0qM.jpg)

Right now, this project is at the scooter stage -- it has good developer experience and gets a reader from point A to point B with some work. I think my proposal will move the reader experience to the motorcycle. And if GitHub ever relaxes their API or constraints, I can deliver an automobile.

I would like to stage the development of this feature to increase the user delight:

1. Add a comment form
1. Add a preview button
1. Add a *Copy to Clipboard* button
1. Add the OAuth input field, change the clipboard button to a *Submit* button
1. Add OAuth creation help
1. Add OAuth validation and feedback

### Gaps

* I still cannot provide a way for anonymous comments the way GitHub Gists permit.

**Comment by wireddown** [comment]
So here's a teaser -- https://github.com/wireddown/github-api-exercise/issues/6

;-)

**Comment by naveenshaji** [comment]
404 here:
>http://downtothewire.io/2015/01/01/second-post-cos-its-cool

is this expected?

**Comment by wireddown** [comment]
Yes. My link was unclear: the *comments* on the issue show I've been able to post a comment from the blog page.

The issue's blog post doesn't exist - that repository is a scratch target for API practice. It lets me experiment with the API and not clutter genuine sites.

**Comment by wireddown** [comment]
Ok! I have a preview page for this feature:

http://downtothewire.io/ghpages-ghcomments/preview/comments/

@naveenshaji and @philippneugebauer: if you get a chance in the next day or two, please try to use/comment on the page and give me your feedback.

**Comment by philippneugebauer** [comment]
At the beginning it felt like the switch between write and preview was stucking. Additionally, in my opinion the difference between selected and not selected is not intuitive. I thought a while you had interchanged both buttons.

Do I need to write down the oath key all the time?

In general, it looks quite good, but I'm not sure, if the copy&paste of the oauth is really convenient :/

**Comment by naveenshaji** [comment]
Nice. 

What are the scopes required for the token?

Also, On first entering the token, you need to press submit twice. Once when the token is accepted. Second time to submit the comment. Is it not redundant, since the first time itself, the users would expect it to submit comment?

**Comment by wireddown** [comment]
Awesome, thanks for responding so quickly. I'd like a little more information.

#### For both of you:

* Which browser(s) did you use?
* What OS(es) did you use?

**My testing so far has been:**

* Firefox on Windows
* Chrome on Windows
* Chrome on Android 4.4 phone
* Chrome on Android 4.2 tablet

#### Philipp

> *@philippneugebauer wrote:*
>
> At the beginning it felt like the switch between write and preview was stucking.

Are you saying you noticed a delay when you switched modes between *Write* and *Preview*? Would you be albe to provide a small example with [LICECap](http://www.cockos.com/licecap/)?

> Additionally, in my opinion the difference between selected and not selected is not intuitive. I thought a while you had interchanged both buttons.

About how long were you confused, and what mouse movements, clicks, or finger taps did you use to explore the interaction?

> Do I need to write down the oath key all the time?

No. In my testing, as soon as the token is valid, the page places it in [localStorage](https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Storage#localStorage) and then hides the text entry field.

Did the token entry field remain visible once you entered it?

> I'm not sure, if the copy&paste of the oauth is really convenient :/

I hear you on this point. The **new** reader still has a moderate task to complete before they comment, which can discourage them from participating:

1. Create a GitHub account if they don't already have one. *(I cannot address this until GitHub allows service accounts or anonymous comments.)*
1. Create an OAuth token for the blog site to use. *(This could be a further enhancement, although allowing users with two-factor authentication will make this significant.)*
1. Copy/Paste the token into the field on the blog site.

#### Naveen

> *@naveenshaji wrote:*
>
> What are the scopes required for the token?

I'm still determining the minimum viable set, but these are API entry points that use the token:

* `/user` (GET)
* `/markdown` (POST)
* `/search` (GET)
* `/repos` (GET and POST)

When this feature is released, I will also provide some guidance for the readers. I will link to the GitHub instructions for creating a Token, but will also provide a description of how the site uses the token and which scopes must be included.

> On first entering the token, you need to press submit twice. Once when the token is accepted. Second time to submit the comment.

This surprises me. Would you be able to provide a small example with [LICECap](http://www.cockos.com/licecap/) that shows the behavior you described? To reset the comments page, use a Private/Incognito tab or a different browser.

I expected this work flow, text and GIF:

1. Load the page. The comment entry field and token entry field are visible. The *Write* and *Preview* boxes are enabled and you can switch between then. The *Submit* button is **disabled** and it cannot be clicked or tapped.
1. Enter the OAuth token. The token entry field *disappears* and the *Submit* button is **enabled**.
1. Type the comment, preview it. This step is also possible *before* entering the token.
1. Click or tap the *Submit* button.
1. The new comment appears on the page and the comment form is reset for a new comment.

![commentinteractions](https://cloud.githubusercontent.com/assets/8404598/6432772/050fd718-c023-11e4-9f69-d021f407bae8.gif)

**Comment by naveenshaji** [comment]
I used Chrome on Windows 7. I will try getting a GIF as soon as I can.

**Comment by naveenshaji** [comment]
On further testing, I found that, you don't need to press submit twice. It was my bad. The first time I tried, I had clicked on the disabled submit button, during the delay in which my token was validated, and had thought that my click led to the change. I was mistaken. But it would be great if you could add a white overlay with 0.7 opacity or so, while the OAuth is being validated. The delay might create confusion.

**Comment by wireddown** [comment]
Great, thanks for spending more time on this :-)

> But it would be great if you could add a white overlay with 0.7 opacity or so, while the OAuth is being validated.

What has the overlay -- the *Submit* button or another element?

**Comment by wireddown** [comment]
To provide feedback on latent connections, I re-used a few UI elements:

The help message <div> in the comment form for when the user:
* When the user posts a comment, the message says *Posting comment...*
* When the user enters a 40-characater OAuth token, the message says *Checking token...*

**Comment by naveenshaji** [comment]
Nice  :-)  Now it feels much better.

I was browsing github when I stumbled on [this](https://github.com/prose/gatekeeper)

> Because of some security-related limitations, Github prevents you from implementing the OAuth Web Application Flow on a client-side only application.
>This is a real bummer. So we built Gatekeeper, which is the missing piece you need in order to make it work.

Is this feasible on gh-pages, for getting OAuth?

**Comment by wireddown** [comment]
> *@naveenshaji wrote:*
>
> I was browsing github when I stumbled on [this](https://github.com/prose/gatekeeper)
>
> > Because of some security-related limitations, Github prevents you from implementing the OAuth Web Application Flow on a client-side only application. This is a real bummer. So we built Gatekeeper, which is the missing piece you need in order to make it work.
>
> Is this feasible on gh-pages, for getting OAuth?

I'm not sure yet, but I hope to evaluate that possibility this week. As you found, Gatekeeper claims it supports client-side only authentication.

My largest worry is that the redirect middle step (by way of Heroku or Azure) assumes that the site is also hosted by Heroku or Azure. In other words, a `gh-pages` site, which is hosted by GitHub, would not be able receive the authorization from the Heroku or Azure waypoint.

**Comment by wireddown** [comment]
## Success!

Using Gatekeeper works :-)

1. I set up a single-dyno Heroku instance and deployed Gatekeeper to it.
1. I updated the preview page to use the OAuth [web-application flow](https://developer.github.com/v3/oauth/#web-application-flow).
1. I was able to [login and post](https://github.com/wireddown/ghpages-ghcomments/issues/15#issuecomment-77990470) a new comment.
1. I also tested using a new browser, which triggered GitHub's [two-factor authentication](https://help.github.com/articles/about-two-factor-authentication/).

## Please test it

If you have already used a token, then the preview page will remember you. Clear you token by:
 * deleting your cookies for http://downtothewire.io, *or*
 * using the browser's console: `localStorage.clear();` ([Firefox](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console) and [Chrome](https://developer.chrome.com/devtools/docs/console))

Then, reload the page.

**Comment by naveenshaji** [comment]
Well done. It seems like a complete fluid use-flow now. For latent connections there is too much of a delay from when the pop-up window closes to the time it shows my name and all. Can you do something like how you added the message showing _validating..._ earlier

**Comment by wireddown** [comment]
> Well done. It seems like a complete fluid use-flow now. For latent connections there is too much of a delay from when the pop-up window closes to the time it shows my name and all. Can you do something like how you added the message showing validating... earlier

Added. I mimicked a slow connection via Google Chrome's simulated-handset throttling console tool, but I forgot about a Heroku *detail*...

**Please test again :-)**

> I am not too familiar with the way Heroku works. Is there anything someone who would want to include ghpages-ghcomments to his/her gh-blog should know regarding this?

First, the detail I mentioned above -- single- and dual-dyno instances will [go to sleep](https://devcenter.heroku.com/articles/dynos#dyno-sleeping) after one hour of inactivity, which incurs a 1-2 second delay the first time they are used. You likely experienced that delay.

Second, the way Gatekeeper is written right now, *ghpages-ghcomments* can serve as the intermediate GitHub authorization conduit for all blog owners, with two caveats:

1. The only free Heroku instance is a single-dyno instance, which is of course constrained in CPU and memory. Gatekeeper is lightweight and written in Node.js, and while Heroku [claims 1000s of requests per second per dyno](https://devcenter.heroku.com/articles/dynos#dynos-and-requests), I wouldn't be surprised if Gatekeeper weren't as efficient. Eventually, with enough blog owners, *ghpages-ghcomments* will appear to slow down. The counter argument is: this service is only used when a user logs in for the **first time**, and not every time. In other words, for a user to notice a slow down, 50 or more must near-simultaneously authenticate.

2. Some blog owners don't want or cannot allow a third-party (*ghpages-ghcomments* or *Heroku*) to mediate between their users and GitHub. They might be worried about man-in-the-middle attacks or have another concern. For those blog owners, I can write a how-to post so they can set up their own Gatekeeper instance (on Heroku, or their own server, or another service).

**Comment by naveenshaji** [comment]
> Some blog owners don't want or cannot allow a third-party (ghpages-ghcomments or Heroku) to mediate between their users and GitHub. They might be worried about man-in-the-middle attacks or have another concern. For those blog owners, I can write a how-to post so they can set up their own Gatekeeper instance (on Heroku, or their own server, or another service).

Thats great!! So people who can get better dynos won't have to cope with the delay due to sleep.

> Please test again :-)

Yup, feels right now.

Also, when can a release be expected?

**Comment by wireddown** [comment]
> Also, when can a release be expected?

I believe I can release by March 21st at the latest. Here's the remaining work as I see it:

* Simplify the code and CSS
* Add options for private Gatekeeper instances
* Update the setup and uninstall instructions
* Add Gatekeeper instructions
* Update the troubleshooting and diagnostics pages
* Update the manual page

I need to do the first four to consider enough complete for others to use.

**Comment by naveenshaji** [comment]
> I believe I can release by March 21st at the latest.

Great! Looking forward to it. 

I'd love to include this in a jekyll theme I'm building now. Sneak a peek [here](http://naveenshaji.github.io/material/).

**Comment by wireddown** [comment]
### Update

Here's the remaining work:

* ~~Simplify the code and CSS~~
* ~~Add options for private Gatekeeper instances~~
* ~~Update the setup and uninstall instructions~~
* Add Gatekeeper instructions
* Update the troubleshooting and diagnostics pages
* Update the manual page

**Comment by wireddown** [comment]
### Update

On-page comments have been released!

http://downtothewire.io/ghpages-ghcomments/setup/

#### Here's the remaining work:

* ~~Simplify the code and CSS~~
* ~~Add options for private Gatekeeper instances~~
* ~~Update the setup and uninstall instructions~~
* ~~Add Gatekeeper instructions~~
* Update the troubleshooting and diagnostics pages
* Update the manual page

**Comment by philippneugebauer** [comment]
I was busy the last time, but I will have a look the next time. Anyways, your progress sounds really great!

**Comment by naveenshaji** [comment]
Looking great!

But does this work if the author is committing via GitHub web UI rather than from git locally?

**Comment by wireddown** [comment]
> But does this work if the author is committing via GitHub web UI rather than from git locally?

This sounds like a different topic than commenting directly on the blog page. Are you asking about using the GitHub ["edit file" page](https://help.github.com/articles/editing-files-in-your-repository/) or GitHub ["add file" page](https://help.github.com/articles/creating-new-files/) to trigger the creation of the page's comment issue?

If so, it might be possible by using [GitHub web hooks](https://developer.github.com/webhooks/). The `push` event seems like it would be triggered when a repository file has been added or edited and committed. A Heroku web dyno could receive that hook callback and use the GitHub API to create an issue for that new page on the owner's behalf. The git hooks that *ghpages-ghcomments* employs use an OAuth token to create issues from the command line, and I see no reason why a Heroku web app would be limited. The largest uncertainty is receiving a web hook callback when a file is edited or added.

> Can a page hosted on gh-pages make a commit with a file edit/create to a GitHub repository, assuming the user provides an OAuth key that has write access to said repository?

Yes, and there are two security measures in place:

1. The OAuth token represents a GitHub user, and it limits the actions that user can take via access scopes
1. The repository owner can grant write access to other GitHub users.

In other words, having a token with write access to a repository is not enough -- the user represented by that token must also have write access.

**Comment by wireddown** [comment]
### Update

Here's the remaining work:

* ~~Simplify the code and CSS~~
* ~~Add options for private Gatekeeper instances~~
* ~~Update the setup and uninstall instructions~~
* ~~Add Gatekeeper instructions~~
* ~~Update the troubleshooting and diagnostics pages~~
* Update the manual page

**Comment by wireddown** [comment]
I've updated the manual page. This feature is complete :-)
